# Generated by Django 4.1.5 on 2023-01-19 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="healthtips",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("tips", models.CharField(max_length=50)),
                ("tip_description", models.TextField()),
            ],
        ),
    ]
